apply plugin: 'com.android.application'

android {
    namespace "chat.richclient"
    compileSdk versions.compileSdk

    defaultConfig {
        applicationId "chat.richclient"
        minSdk versions.minSdk
        targetSdk versions.targetSdk
        versionCode 1
        versionName "0.1.0"
    }

    compileOptions {
        sourceCompatibility versions.sourceCompat
        targetCompatibility versions.targetCompat
    }
}

dependencies {
    implementation libs.androidx.recyclerview
    implementation libs.androidx.appCompat
    implementation libs.google.material
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'com.github.UnifiedPush:android-connector:2.1.1'
    implementation libs.markwon.core
    implementation libs.markwon.extTables
    implementation libs.markwon.extLatex
    implementation libs.markwon.html
    implementation libs.markwon.inlineParser

    testImplementation libs.tests.junit
    testImplementation 'org.json:json:20240303'
}
